### ISSUE TITLE
Tree collision with ground sounds only play for the first tree that hits the ground

### ISSUE THREAD

**Issue by fonnymunkey** [TerraFirmaCraft-The-Final-Frontier/DramaticTrees#14]
**Description**

When you chop down trees, only the first time any tree collides with the ground the sound will play, all trees after do not play the sound.

**To Reproduce**

Chop down a tree, sound plays when the tree finishes falling, chop down more trees, no sound.

**Additional Context**

AnimationHandlerFallover is handled as a single instance: 
https://github.com/TerraFirmaCraft-The-Final-Frontier/DramaticTrees/blob/release/1.12.2/src/main/java/com/ferreusveritas/dynamictrees/entities/animation/AnimationHandlers.java#L52
However, fallSound: 
https://github.com/TerraFirmaCraft-The-Final-Frontier/DramaticTrees/blob/release/1.12.2/src/main/java/com/ferreusveritas/dynamictrees/entities/animation/AnimationHandlerFallover.java#L37
is treated as though there is an instance of AnimationHandlerFallover per each tree falling.
In theory fallSound limits trees to only play a single collision sound per tree, but in practice due to this issue fallSound is never reset and thus restricts the collision sound to only the first tree to collide with the ground.

- Dynamic Trees: 0.13.3
- Forge: 2860
- Java: 8
- OS: W10

**Comment by fonnymunkey** [comment]
I have created a patch in RLMixins that indirectly fixes this, as instead of tracking fallSound and limiting it to once per tree collision, I play the collision sounds volume proportional to the tree's falling speed when the collision happens, to allow for multiple collision sounds that sound more realistic when bouncing on multiple blocks.
I can turn this patch into a PR if that is desired.

**Comment by ACGaming** [comment]
Feel free to provide the suggested changes as this is still somewhat maintained.
