### ISSUE TITLE
Load to PHC report error 

### ISSUE THREAD

**Issue by Lonelyxiya** [TerraFirmaCraft-The-Final-Frontier/DramaticTrees#4]
[crash-2022-11-27_13.49.42-client.txt](https://github.com/TerraFirmaCraft-The-Final-Frontier/DramaticTrees/files/10097627/crash-2022-11-27_13.49.42-client.txt)
loading Dynamic Trees PHC report error  pls
Please fix this problem as soon as possible, there is no such problem in the official version of Dynamic Trees.

**Comment by ACGaming** [comment]
You‘re using an outdated version of Dynamic Trees PHC, please update to [version 2.0.6](https://www.curseforge.com/minecraft/mc-mods/dtphc/files/3812463).
